// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: order.sql

package datastore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(total_amount, tax, client_name, client_email, client_phone, note)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateOrderParams struct {
	TotalAmount pgtype.Numeric
	Tax         pgtype.Numeric
	ClientName  pgtype.Text
	ClientEmail pgtype.Text
	ClientPhone pgtype.Text
	Note        pgtype.Text
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.TotalAmount,
		arg.Tax,
		arg.ClientName,
		arg.ClientEmail,
		arg.ClientPhone,
		arg.Note,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

type CreateOrderItemsParams struct {
	UnitPrice pgtype.Numeric
	ProductID int32
	Quantity  int32
	OrderID   int32
}

const getOrder = `-- name: GetOrder :one
SELECT id, status, total_amount, tax, created, shipped, cancelled, delivered, client_name, client_email, client_phone, note, cancellation_reason FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.Tax,
		&i.Created,
		&i.Shipped,
		&i.Cancelled,
		&i.Delivered,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Note,
		&i.CancellationReason,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, status, total_amount, tax, created, shipped, cancelled, delivered, client_name, client_email, client_phone, note, cancellation_reason FROM orders
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Tax,
			&i.Created,
			&i.Shipped,
			&i.Cancelled,
			&i.Delivered,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.Note,
			&i.CancellationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int32
	Status OrderStatus
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
