version: '3'

services:
  db:
    command: ["postgres", "-c", "log_statement=mod"]
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_DB_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    container_name: buddysellerdb
    volumes:
      - ./postgres:/var/lib/postgresql/data